### ISSUE TITLE
Having `gradlew[.bat]` without `gradle` folder is brocken state

### ISSUE THREAD

**Issue by paulvi** [marshallino16/FloatingView#4]
There should be either `gradle` folder or `gradlew[.bat]` should be removed.

@marshallino16 Anthony, do you need PR for that?
I can update build to latest.

**Comment by marshallino16** [comment]
Yes please PR the deletion, actually i don't even use Gradle.

**Comment by paulvi** [comment]
done #5 as adding missing `gradle` folder

**Comment by marshallino16** [comment]
Thank you.
